### ISSUE TITLE
Code add New Debtors

### ISSUE THREAD

**Issue by Thatslimdev** [zuri-training/My_debtors_Team35#31]
figma link: https://www.figma.com/file/dOQv8d0yWU9BU7Adea2LIU/TEAM35_MY_DEBTORS?node-id=1056%3A1630

Reply done when this task is complete

**Comment by Dennardavid** [comment]
Done

**Comment by Dennardavid** [comment]
These are some of my contributions to the project :
https://github.com/zuri-training/My_debtors_Team35/blob/main/Frontend/studebt/public/templates/Adddebtors.html
https://github.com/zuri-training/My_debtors_Team35/blob/main/Frontend/studebt/public/templates/success.html
https://github.com/zuri-training/My_debtors_Team35/blob/main/Frontend/studebt/public/templates/error.html
https://github.com/zuri-training/My_debtors_Team35/blob/main/Frontend/studebt/public/templates/debtdetails.html 
https://github.com/zuri-training/My_debtors_Team35/commit/d64eb5a1904e7fe2052a1a96cff76b83e74af0ac
https://github.com/zuri-training/My_debtors_Team35/commit/c815dd9ffba8736c5ca5e904a1db53537876dbbb
